#!/usr/bin/env bash
# NOTE(dabrady) Run this from the project root directory
cd ./test || exit
source approvals.bash

### Helpers

# NOTE(dabrady) Don't edit this directly: update the `end` helper function.
cli=

# Use this at the very beginning, prior to running any tests
setup_test_env() {
  export NOOP=true
  TEST_FLAGS=
  CLI="../cli${TEST_FLAGS}" # Path to CLI, relative to this file

  cli=$CLI
}

# Use at the end of a `context` block to reset to original test config
end() {
  setup_test_env
}

### Tests (context, describe and indentation are optional)

setup_test_env

describe "root command"
  approve "$cli"
  approve "$cli --version"
  approve "$cli --help"

context 'when no global flags are specified'
  describe 'command: `suites`'
    approve "$cli suites"
    approve "$cli suites --help"

  describe 'command: `suites ls`'
    approve "$cli suites ls"
    approve "$cli suites ls --help"

  describe 'command: `suites run`'
    approve "$cli suites run"
    approve "$cli suites run --help"

  describe 'command: `suites progress`'
    approve "$cli suites progress"
    approve "$cli suites progress --help"
end

context 'when `--json` is specified'
  ## Context Setup
  cli="$cli --json"

  ## Approvals
  describe 'command: `suites ls`'
    approve "$cli suites ls"

  describe 'command: `suites run`'
    approve "$cli suites run"

  describe 'command: `suites progress`'
    approve "$cli suites progress"
end
